# Generated by @sdlcforge/gen-make v1.0.0-alpha.0
# Do not edit manually - regenerate with gen-make
# Generated: 2026-04-08T22:27:34.278Z

.DELETE_ON_ERROR:

SHELL:=bash

default: all
.PHONY: default all

BUILD_TARGETS:=
DOC_TARGETS:=
LINT_TARGETS:=
TEST_TARGETS:=
PRECIOUS_TARGETS:=

ifneq ($(wildcard make/*.mk),)
include make/*.mk
endif

# @sdlcforge/gen-make hash: ae5b752aa63d
