# Generated by @sdlcforge/gen-make v1.0.0-alpha.0
# Do not edit manually - regenerate with gen-make
# Generated: 2026-04-10T02:46:36.954Z

#####
# Directory locations
#####

SRC:=src
DIST:=dist
TESTS:=tests
TEST_STAGING:=test-staging
QA:=qa
BIN:=bin

#####
# Bash tools
#####

SDLC_BASH_ROLLUP:=npx bash-rollup
SDLC_SHELLCHECK:=shellcheck
SDLC_SHELLSPEC:=shellspec

# @sdlcforge/gen-make hash: 62f04e5b7041
