# Generated by @sdlcforge/gen-make v1.0.0-alpha.0
# Do not edit manually - regenerate with gen-make
# Generated: 2026-04-07T18:59:19.381Z

#####
# Shell file discovery
#####

SDLC_SHELL_SRC_FILES:=$(shell find $(SRC) -type f -name '*.sh' 2>/dev/null)
# Project-wide lint scope: every .sh anywhere except generated/output dirs
SDLC_ALL_SHELL_FILES:=$(shell find . -type f -name '*.sh' \
	-not -path './node_modules/*' \
	-not -path './$(DIST)/*' \
	-not -path './$(TEST_STAGING)/*' \
	-not -path './$(BIN)/*' \
	-not -path './.git/*' 2>/dev/null)
SHELL_TESTS:=test
SDLC_INTEGRATION_SHELL_TEST_FILES:=$(shell find $(SHELL_TESTS)/integration -type f -name '*_spec.sh' 2>/dev/null)
SDLC_UNIT_SHELL_TEST_FILES:=$(shell find $(SHELL_TESTS)/unit -type f -name '*_spec.sh' 2>/dev/null)

# @sdlcforge/gen-make hash: f557b7c15673
