# Generated by @sdlcforge/gen-make v1.0.0-alpha.0
# Do not edit manually - regenerate with gen-make
# Generated: 2026-04-07T18:59:19.381Z

#####
# build bin/ai-sandbox.sh
#####

SDLC_AI_SANDBOX_BASH:=bin/ai-sandbox.sh
SDLC_AI_SANDBOX_BASH_ENTRY:=$(SRC)/index.sh
BUILD_TARGETS+=$(SDLC_AI_SANDBOX_BASH)

$(SDLC_AI_SANDBOX_BASH): $(SDLC_AI_SANDBOX_BASH_ENTRY) $(SDLC_SHELL_SRC_FILES)
	@mkdir -p $(dir $@)
	$(SDLC_BASH_ROLLUP) $(SDLC_AI_SANDBOX_BASH_ENTRY) $@

#####
# end bin/ai-sandbox.sh
#####

# @sdlcforge/gen-make hash: ecd87f836afb
