# Generated by @sdlcforge/gen-make v1.0.0-alpha.0
# Do not edit manually - regenerate with gen-make
# Generated: 2026-04-07T18:59:19.381Z

#####
# Shell lint rules
#####

SDLC_SHELL_LINT_REPORT:=$(QA)/shell-lint.txt
SDLC_SHELL_LINT_PASS_MARKER:=$(QA)/.shell-lint.passed
LINT_TARGETS+=$(SDLC_SHELL_LINT_REPORT) $(SDLC_SHELL_LINT_PASS_MARKER)

.PRECIOUS: $(SDLC_SHELL_LINT_REPORT)

$(SDLC_SHELL_LINT_REPORT) $(SDLC_SHELL_LINT_PASS_MARKER): $(SDLC_ALL_SHELL_FILES)
	@mkdir -p $(dir $@)
	( set -e; set -o pipefail; \
	  $(SDLC_SHELLCHECK) -P $(SRC) $(SDLC_ALL_SHELL_FILES) \
	    | tee $(SDLC_SHELL_LINT_REPORT); \
	  touch $(SDLC_SHELL_LINT_PASS_MARKER) )

#####
# end shell lint
#####

# @sdlcforge/gen-make hash: 230bcf6073f3
