# Generated by @sdlcforge/gen-make v1.0.0-alpha.0
# Do not edit manually - regenerate with gen-make
# Generated: 2026-04-07T18:59:19.381Z

#####
# integration shell tests
#####

SDLC_INTEGRATION_SHELL_TEST_REPORT:=$(QA)/integration-shell-test.txt
SDLC_INTEGRATION_SHELL_TEST_PASS_MARKER:=$(QA)/.integration-shell-test.passed
SDLC_INTEGRATION_SHELL_TEST_TARGETS:=$(SDLC_INTEGRATION_SHELL_TEST_REPORT) $(SDLC_INTEGRATION_SHELL_TEST_PASS_MARKER)
TEST_TARGETS+=$(SDLC_INTEGRATION_SHELL_TEST_REPORT) $(SDLC_INTEGRATION_SHELL_TEST_PASS_MARKER)

.PRECIOUS: $(SDLC_INTEGRATION_SHELL_TEST_REPORT)

$(SDLC_INTEGRATION_SHELL_TEST_REPORT) $(SDLC_INTEGRATION_SHELL_TEST_PASS_MARKER) &: $(SDLC_INTEGRATION_SHELL_TEST_FILES) $(BUILD_TARGETS)
	@mkdir -p $(dir $@)
	( set -e; set -o pipefail; \
	  $(SDLC_SHELLSPEC) $(SHELL_TESTS)/integration \
	    | tee $(SDLC_INTEGRATION_SHELL_TEST_REPORT); \
	  touch $(SDLC_INTEGRATION_SHELL_TEST_PASS_MARKER) )

#####
# end integration shell tests
#####

# @sdlcforge/gen-make hash: 305f7ef684ee
