# Generated by @sdlcforge/gen-make v1.0.0-alpha.0
# Do not edit manually - regenerate with gen-make
# Generated: 2026-04-07T18:59:19.381Z

#####
# unit shell tests
#####

SDLC_UNIT_SHELL_TEST_REPORT:=$(QA)/unit-shell-test.txt
SDLC_UNIT_SHELL_TEST_PASS_MARKER:=$(QA)/.unit-shell-test.passed
SDLC_UNIT_SHELL_TEST_TARGETS:=$(SDLC_UNIT_SHELL_TEST_REPORT) $(SDLC_UNIT_SHELL_TEST_PASS_MARKER)
TEST_TARGETS+=$(SDLC_UNIT_SHELL_TEST_REPORT) $(SDLC_UNIT_SHELL_TEST_PASS_MARKER)

.PRECIOUS: $(SDLC_UNIT_SHELL_TEST_REPORT)

$(SDLC_UNIT_SHELL_TEST_REPORT) $(SDLC_UNIT_SHELL_TEST_PASS_MARKER) &: $(SDLC_UNIT_SHELL_TEST_FILES) $(BUILD_TARGETS)
	@mkdir -p $(dir $@)
	( set -e; set -o pipefail; \
	  $(SDLC_SHELLSPEC) $(SHELL_TESTS)/unit \
	    | tee $(SDLC_UNIT_SHELL_TEST_REPORT); \
	  touch $(SDLC_UNIT_SHELL_TEST_PASS_MARKER) )

#####
# end unit shell tests
#####

# @sdlcforge/gen-make hash: d899d7ac2b50
