# Generated by @sdlcforge/gen-make v1.0.0-alpha.0
# Do not edit manually - regenerate with gen-make
# Generated: 2026-04-07T18:59:19.381Z

#####
# Final aggregation targets
#####

build: $(BUILD_TARGETS)
.PHONY: build

all: build

test.integration: $(SDLC_INTEGRATION_SHELL_TEST_TARGETS)
.PHONY: test.integration

test.unit: $(SDLC_UNIT_SHELL_TEST_TARGETS)
.PHONY: test.unit

test.all: test.integration test.unit
.PHONY: test.all

test: test.unit
.PHONY: test

lint: $(LINT_TARGETS)
.PHONY: lint

qa: test.all lint
.PHONY: qa

#####
# Clean targets
#####

clean.build:
	@echo "Cleaning build artifacts..."
	@rm -f $(BUILD_TARGETS)
.PHONY: clean.build

clean.qa:
	@echo "Cleaning QA artifacts..."
	@rm -rf $(QA)/*
.PHONY: clean.qa

clean.all: clean.build clean.qa
.PHONY: clean.all

clean: clean.build
.PHONY: clean

# @sdlcforge/gen-make hash: 8b0a1b03748d
